on:
  push:
    branches:
      - main
name: Generate a list of contributors
jobs:
  contrib-readme-en-job:
    if: false
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 80
          use_username: true
          columns_per_row: 8
        env:
          GITHUB_TOKEN: ${{ secrets.LLaVA_OV_CONTRIBUTORS }}
